### ISSUE TITLE
Missing "/" in package.json

### ISSUE THREAD

**Issue by krasimiryanchev** [parkerholladay/node-octopus-deploy#12]
in section:  
"bin": {
    "octopus-deploy-create-release": "./bin/create-release.js",
    "octopus-deploy-create-release-and-deploy": "./bin/create-release-and-deploy.js",
    "octopus-deploy-pack-and-push": ".bin/pack-and-push.js"
  },

... ".bin/pack-and-push.js" should be "./bin/pack-and-push.js"

**Comment by parkerholladay** [comment]
Good catch. Sorry about that.
